searchspring/asanaban

www/index.html
=> More cute thingz

app/components/SetupUI.js, app/model/asana.js, app/other.css
=> don't sync custom fields if they're -1

app/model/asana.js, app/model/asanaban.js, app/views/Kanban.js
This was my second time attempting the lane duplication bug fix and it consisted of 3 things. 
1. Rewriting my first fix with a better understanding of what the code is doing, and making sure my fixes are doing what I think they are. 
2. Cleaning up my first attempt and making the code as readable as I could. 
3. Successfully fixing the "sections not showing newly dragged tasks" bug
I did various tests navigating between various projects and testing all the app features on different boards. Also tested clearing cache. In my testing, I did not come across any other bugs.
=> Successful Attempt at Lane duplication Bug Fix 

app/components/TaskEditor.js
In hindsight, I could have added this change to the other PR but I didn't know it was only gonna be a 1 line change. Also, I need practice with branches, uploading to remote, and PR's :) 
New Task Editor
Old Task Editor
=> Improved the position of the task editor so it's always in view

app/components/Column.js, app/model/asana.js, app/model/asanaban.js, app/views/Kanban.js, package-lock.json, package.json
This PR includes the added feature that all Asanaban boards will now automatically be in sync with the location and content of tasks without having to reload the page.
=> Asana Auto Task Sync

app/model/asana.js
This PR includes the fix to not only update task modifications but to update new tasks created. 
It also changes the period between syncs from 0.5 to 5 seconds.
=> Resolved new task bug

app/model/asana.js
This PR fixes the bug that removes tasks when you drag them to a different location in the same column.
Also tested the application as a whole quite thoroughly and seems to be running smoothly.
=> Fixed same column transfer bug

src/components/TaskEditor.vue, src/components/TextEditor.vue, src/store/asana/index.ts, src/store/preferences/index.ts, src/types/asana.ts
=> Added comment editor

package-lock.json, package.json, src/components/Task.vue, src/store/asana/index.ts, src/store/asana/state.ts
=> Fade old tasks

package-lock.json, package.json, src/components/DateSelector.vue, src/components/TaskEditor.vue, src/store/preferences/index.ts, src/types/asana.ts, src/utils/date.ts
=> Switched to Naive UI date selector

src/store/asana/index.ts, src/utils/asana-specific.ts
=> Changed color to hex converter to display prettier Asana tag colors

src/components/AssigneeSelector.vue, src/components/TagSelector.vue, src/components/Task.vue, src/components/TaskEditor.vue, src/store/asana/index.ts, src/store/preferences/index.ts, src/types/vue.ts
Task Editor view of Assignee Selector:
Task view of task with assignee:
=> Switched Assignee Selector to Naive UI and changed assignee task view

src/components/Task.vue
Fixed bug where task detail edits would stay even when user would click cancel.
=> Fix task editor cancel

src/components/MenuBar.vue, src/components/Stories.vue, src/components/Task.vue, src/components/TaskEditor.vue, src/components/TextEditor.vue
Made UI spacing smaller in text editor and styled buttons, stories, and text editor components on task editor:
=> Fixed text editor spacing and styled task editor

.gitignore, .golangci.yml, Dockerfile, Makefile, go.mod, go.sum, src/store/asana/worker.ts
- Upgrade to go 1.18
- Add try/catch and some field checks for the worker to make it more resilient to errors that can stop processing
---
- https://app.asana.com/0/0/1202081756487359
=> Resilient worker

package-lock.json, package.json, src/components/Task.vue, src/components/TaskEditor.vue, src/store/asana/index.ts, src/types/asana.ts
We show an icon for subtasks on the summary (board) level. We also show the list of tasks on the detail (editor) view
---
- https://app.asana.com/0/0/1201913676292410
=> Display subtask info

src/App.vue, src/components/Actions.vue, src/components/Column.vue, src/components/ProjectSelector.vue, src/components/Search.vue, src/components/SignIn.vue, src/components/Swimlane.vue, src/components/Task.vue, src/components/TaskEditor.vue, src/components/TextEditor.vue
- Added some padding/margins to some elements (to distinguish) and removed some others (to maximize space)
- Made the column headers slightly more distinguished from the body
- Search task and project selector now use naive-ui components
- Added a bit of style to the "show errors" from actions/tasks
- Moved sign out button to the right
- Increased task description textarea height
=> Various UX changes

src/components/Column.vue
Note: the majority of the changed lines are because of the formatter. taskCountForSameNameColumn is the key change
=> Fix: column over limit checks now look at all columns of same name

src/App.vue, src/components/BackgroundSelector.vue, src/components/Column.vue, src/store/preferences/index.ts, src/store/preferences/state.ts
This is 90% copied from the old asanaban version
=> Allow user to select the background

src/components/Column.vue, src/components/Stories.vue, src/store/asana/index.ts, src/store/asana/state.ts
Also tweaked the background colours to be a bit nicer looking
=> Adding a loading indicator to the story loading

src/components/Task.vue, src/components/TaskEditor.vue, src/store/asana/index.ts, src/types/asana.ts, src/utils/custom-fields.ts
---
- https://app.asana.com/0/0/1202227333714421
=> Tasks now saved properly

src/components/Column.vue
Expanded the padding of the text and removed the padding on the div.
---
- https://app.asana.com/0/0/1202246717832746
=> Remove whitespace on collapsed column.

src/App.vue, src/components/Column.vue, src/components/Stories.vue, src/components/Task.vue, src/components/TaskEditor.vue, src/store/asana/index.ts, src/store/asana/state.ts, src/types/asana.ts, src/utils/match.ts, src/views/Home.vue
- Most recent image appear on all tasks.
- The task editor show all images and opens to a new tab when clicked.
---
- https://app.asana.com/0/0/1202156774879466
=> Display images

src/components/Stories.vue, src/store/asana/index.ts, src/types/asana.ts
Added the trash icon to delete comments
Co-authored-by: Albert Lay <albertjlay@gmail.com
>
---
- https://app.asana.com/0/0/1202263404591823
=> Able to delete comments

src/components/Stories.vue, src/components/TaskEditor.vue, src/components/TaskProjectSelector.vue, src/store/asana/index.ts, src/types/asana.ts, src/utils/asana-specific.ts
---
- https://app.asana.com/0/0/1202263313670273
=> Users can add/remove projects from a task
